# InstrumentTimbre Configuration
# Simplified configuration for Chinese instrument classification

# Data settings
data:
  train_split: 0.8
  use_chinese_features: true
  sample_rate: 22050

# Feature extraction
features:
  sample_rate: 22050
  hop_length: 512
  n_fft: 2048
  n_mfcc: 50

# Model configuration
model:
  type: enhanced_cnn
  input_dim: 128
  hidden_dims: [256, 512, 256, 128]
  fc_dims: [512, 256]
  num_classes: 5
  dropout_rate: 0.1
  use_batch_norm: true
  use_residual: true
  use_attention: true

# Training settings
training:
  epochs: 100
  batch_size: 4  # Smaller batch size for small datasets
  optimizer:
    name: adamw
    lr: 0.001
    weight_decay: 0.01
  scheduler:
    name: warmup_cosine
    warmup_epochs: 10
    max_epochs: 100
  patience: 15
  device: auto
  use_tensorboard: false  # Disabled to avoid dependency issues