name: CI

on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install .[develop]
      - name: Lint with flake8
        run: |
          flake8 InstrumentTimbre
      - name: Format with black (check only)
        run: |
          black --check InstrumentTimbre
      - name: Run tests
        run: |
          pytest
